service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 256
  timeout: 120
  iamRoleStatements:
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
  environment:
    FOO: ${self:custom.kmsSecrets.secrets.FOO}

plugins:
  - serverless-kms-secrets

custom:
  stage-name: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

  serverless-kms-secrets:
    secretsFile: aws/kms-secrets.${self:custom.stage-name}.${self:custom.region}.yml
  kmsSecrets: ${file(${self:custom.serverless-kms-secrets.secretsFile})}

  stages:
    development:
    staging:
    production:

  stage: ${self:custom.stages.${self:custom.stage-name}}

functions:
  hello:
    handler: src/functions/hello.handler
